# Generated by Django 2.0 on 2021-09-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='is_read',
            new_name='answered',
        ),
        migrations.AddField(
            model_name='message',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='freeze',
            field=models.BooleanField(default=False),
        ),
    ]
